version: "3"
services:
  nexus:
    image: sonatype/nexus3:3.21.1
    ports:
    - "3001:8081"
    volumes:
    - "./nexus-data:/nexus-data"
  athens:
    image: gomods/athens:v0.7.2
    ports:
    - "3000:3000"
